-- 1. Create this user first in Supabase Auth:
--    admin@farecoh.org
--
-- 2. Replace AUTH_USER_UUID with the auth.users.id generated by Supabase.

insert into public.staff_profiles (user_id, email, full_name, role, active)
values ('AUTH_USER_UUID', 'admin@farecoh.org', 'FARECOH Admin', 'super_admin', true)
on conflict (email) do update set
  user_id = excluded.user_id,
  full_name = excluded.full_name,
  role = excluded.role,
  active = excluded.active;